### ISSUE TITLE
Admin right

### ISSUE THREAD

**Issue by szabozoltan69** [IFRCGo/global-services#65]
Hello @danbjoseph
In the near future I have to do some domain management on this page.
Could you grant me permission for this? (So that I can manage the /settings page.)
No sure, but maybe a redirection to go.ifrc.org/deployments/catalogue would be the request.

**Comment by nanometrenat** [comment]
@szabozoltan69 is this ticket still needed or can we close?  Cheers

**Comment by szabozoltan69** [comment]
Thanks @nanometrenat – we can close this. :-)
